tls:
  options:
    default:
      minVersion: "VersionTLS12"
    mintls13:
      minVersion: "VersionTLS13"

  stores:
    default:
      defaultCertificate:
        certFile: "/etc/traefik/acme/local.crt"
        keyFile: "/etc/traefik/acme/local.key"
