global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true

api:
  insecure: false
  dashboard: true
  debug: false

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
          permanent: true

  https:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    swarmMode: false
    network: external
  file:
    filename: "/dynamic.yml"
    watch: false

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: "andy@welove9am.com"
#      storage: "acme.json"
#      httpChallenge:
#        entryPoint: http
